### ISSUE TITLE
Getting a specific representation doesn't work

### ISSUE THREAD

**Issue by chlmarchal** [Cytomine-ULiege/pims#17]
I noticed that when I try to get the information about one specific image representation ("macro", "label" or "thumb"), the if conditions are not satisfied. Indeed, it compares a FileRole object to a string object and not two string objects.

https://github.com/Cytomine-ULiege/pims/blob/master/pims/files/file.py#L170-L180

**Comment by urubens** [comment]
Yes, thanks for reporting the issue ! I will fix this asap.

However, "macro", "label" or "thumb" are not file roles (or representation). To clarify, there are 2 distinct concepts:
1. Image representation and role: different files for the same image content (pixels) but represented differently on disk, each representation being more suited for a particular type of request ("spatial" for 2D visualisation vs "histogram" for example).
2. Associated images, which are a kind of image metadata, such as "macro", "label" and "thumb". They are small images stored into the image metadata.

While I'm writing this, I realize that the concepts are quite close and associated images could be seen as distinct representations but due to role and representation implementation, it implies to save new files or symlinks for every associated image :/
