### ISSUE TITLE
Problem when fetching processed duplicated files with different extensions

### ISSUE THREAD

**Issue by chlmarchal** [Cytomine-ULiege/pims#18]
Hi! 

When trying to integrate a new fomat plugin in PIMS, I encountered the issue that when I import the images to use them in PIMS, the engine of the format creates files with other extensions than the format itself. This way, I had several files called original.{extension} in the processed folder. In my case, I have two files original.fic and original.ISYNTAX that have been created. The issue is thus that the `get_original()` function (in pims/pims/files/file.py) looks for the first file called 'original'. To resolve this issue, I added a condition to take into account the fact that the extensions of both the parent and the child files must be the same.

This worked for the format I wanted to integrate. However, this caused some issues concerning the MRXS format since the parent file has a .zip extension while the child file has a .MRXS extension. To solve this issue, I added an additional condition to take into account the particular case of the MRXS format.

Here is the piece of code I changed to take into account the issues I encountered: 

```
if self.extension.lower() == ".zip":
            for child in self.processed_root().iterdir():
                if child.has_original_role() and os.path.splitext(child)[1].lower() == ".mrxs":
                    original = child
                    break
                else:
                    original = None
        else:
            original = next((child for child in self.processed_root().iterdir() if (child.has_original_role() and (self.extension.lower()[1:] in os.path.splitext(child)[1].lower()))), None)
```
If you have any suggestion to improve it, feel free to propose :)

**Comment by urubens** [comment]
Hi,
I understand that causes some issues, but it's not clear to me how it is possible to have more than one `original` in the `processed` folder. Is it a multi-file format (like e.g. MRXS, VMS) ?

**Comment by chlmarchal** [comment]
The format I am using is ISYNTAX and it is not a multi-file format. However, when I import my local images to use them in PIMS, I have two `original` files, a `original.fic` file and a `original.ISYNTAX` file. I assume this is due to the format engine itself that creates those `.fic` files during the images importation.

**Comment by urubens** [comment]
Which format engine are you using ? In 'pims' terminology, a format engine is a set of methods that can be re-used across various image format, and I don't think it is involved in the creation of the `original` file representation.

As iSyntax is not a multi-file format, the `upload123/processed/original.ISYNTAX` file is basically a symlink of `upload123/my-file.iSyntax` (https://github.com/Cytomine-ULiege/pims/blob/master/pims/importer/importer.py#L223) 

Part of pims efficiency relies on the fact there is always 1 `original` in the "controlled" directory `processed`. Maybe I'm missing something but I don't get why there are those `.fic` files (and what they are). To me, next step should be to understand the origin of those `.fic` files because they shouldn't be placed in `processed´ and called original.

**Comment by geektortoise** [comment]
My guess is that the SDK that is used to read the iSyntax files create a "metadata cache file" with a fic extension.
We will check that.
