### ISSUE TITLE
Support ZeissCZI format

### ISSUE THREAD

**Issue by urubens** [Cytomine-ULiege/pims#4]
Zeiss CZI format is already supported by Cytomine-IMS

Create a plugin pims-plugin-format-bioformat in GPL

**Comment by geektortoise** [comment]
Hello, 

I have some question about this.
It seems that the CZI is a format that can contain a lot of things with **a lot** of possible dimensions :

_X - Pixel index / offset in the X direction. Used for tiled images.
Y - Pixel index / offset in the Y direction. Used for tiled images.
C - Channel in a Multi-Channel data set
Z - Slice index (Z – direction).
T - Time point in a sequentially acquired series of data.
R - Rotation – used in acquisition modes where the data is recorded from various angles.
S - Scene – for clustering items in X/Y direction (data belonging to contiguous regions of interests in a mosaic image).
I - Illumination - illumination direction index (e.g. from left=0, from right=1).
B - (Acquisition) Block index in segmented experiments.
Note: This index has been dropped. Instead of the B index multiple single CZI images will be generated when saving segmented experiments.
M - Mosaic tile index – this index uniquely identifies all tiles in a specific plane
H - Phase index – for specific acquisition methods.
V - View index (for multi – view images, e.g. SPIM)_

(I don't understand a lot of them -_-' )

Which limitation you see for this support ? XYCZT and set 0 for all the other dimensions ?
A CZI with other dimensions than XYCZT will be split (converted) in multiple ome.tiff ?

**Comment by urubens** [comment]
Hard to say ! I don't understand a lot of them either ;)

I have access to a very small set of CZI images where there is no much variability in the dimensions: only multiple channels and/or z-stack.

The plugin I started for CZI image (https://github.com/Cytomine-ULiege/pims-plugin-format-bioformats) relies on Bioformats with the Cytomine-Bioformats adapter updated for PIMS (https://github.com/Cytomine-ULiege/Cytomine-BioFormats/tree/pims).

Maybe it could help to check what Bio-Formats does because I'm pretty sure they are not handling all these dimensions. By the way, some dimensions seem to be more technical than "true" physical ones like M, S, X?, Y? (?)
